"""Energy plans and SIMULATED usage.

IMPORTANT: none of this data comes from a real meter or electrical grid. Readings are
generated by a deterministic formula (seeded by user id and date) so demos and tests are
reproducible. Every response says is_simulated=true and carries a disclaimer.
"""
import calendar
import math
import random
from collections import defaultdict
from collections.abc import Iterable, Sequence
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal

from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.orm import Session

from app.enums import EnergyStatus
from app.models import EnergyPlan, EnergyUsage, User
from app.schemas.energy import (
    EnergyPlanOut,
    EnergyPlansResponse,
    EnergyReportsResponse,
    EnergyUsageResponse,
    MonthlyReport,
    UsagePoint,
)
from app.utils.errors import BadRequestError
from app.utils.money import to_money

SIMULATION_NOTICE = (
    "SIMULATION: these values are generated for demonstration purposes and do not come "
    "from a real electricity meter or grid."
)
HISTORY_DAYS = 90
ALLOWED_RANGES = (7, 30, 90)
DEFAULT_PLAN_NAME = "Home Standard"

DEFAULT_PLANS: tuple[dict, ...] = (
    {
        "name": "Eco Saver",
        "description": "Lower unit price for small households that use little power.",
        "price_per_kwh": Decimal("2.20"),
        "monthly_fee": Decimal("99.00"),
        "max_kwh": 350,
    },
    {
        "name": DEFAULT_PLAN_NAME,
        "description": "Balanced plan for an average household.",
        "price_per_kwh": Decimal("2.60"),
        "monthly_fee": Decimal("150.00"),
        "max_kwh": 700,
    },
    {
        "name": "Business Power",
        "description": "High-capacity plan for small businesses and workshops.",
        "price_per_kwh": Decimal("2.35"),
        "monthly_fee": Decimal("450.00"),
        "max_kwh": 3000,
    },
)


def utc_today() -> date:
    return datetime.now(timezone.utc).date()


# ---------------------------------------------------------------- plans
def ensure_default_plans(db: Session) -> None:
    """Insert the three seeded plans if they are missing (idempotent, no commit)."""
    existing = set(db.scalars(select(EnergyPlan.name)))
    for spec in DEFAULT_PLANS:
        if spec["name"] not in existing:
            db.add(EnergyPlan(**spec))
    db.flush()


def get_default_plan(db: Session) -> EnergyPlan:
    ensure_default_plans(db)
    return db.scalars(select(EnergyPlan).where(EnergyPlan.name == DEFAULT_PLAN_NAME)).one()


def resolve_plan(db: Session, user: User) -> EnergyPlan:
    return user.energy_plan or get_default_plan(db)


def _plan_to_out(plan: EnergyPlan) -> EnergyPlanOut:
    return EnergyPlanOut(
        id=plan.id,
        name=plan.name,
        description=plan.description,
        price_per_kwh=plan.price_per_kwh,
        monthly_fee=plan.monthly_fee,
        max_kwh=plan.max_kwh,
    )


# ------------------------------------------------------------ simulation
def simulated_kwh(user_id: int, day: date) -> float:
    """Deterministic daily kWh: base load + weekend bump + seasonal wave + small noise."""
    rng = random.Random(f"mmm-energy:{user_id}:{day.isoformat()}")
    base = 12.0 + (user_id % 5) * 1.5
    weekend_bump = 2.5 if day.weekday() >= 5 else 0.0
    seasonal = 3.0 * math.sin(2 * math.pi * day.timetuple().tm_yday / 365.0)
    noise = rng.uniform(-2.0, 2.0)
    return round(max(1.0, base + weekend_bump + seasonal + noise), 2)


def _insert_usage(db: Session, user_id: int, days: Iterable[date]) -> None:
    rows = [
        {"user_id": user_id, "recorded_on": day, "kwh_used": simulated_kwh(user_id, day), "is_simulated": True}
        for day in days
    ]
    if not rows:
        return
    # ON CONFLICT DO NOTHING makes this safe to repeat and safe under concurrent requests.
    statement = (
        pg_insert(EnergyUsage)
        .values(rows)
        .on_conflict_do_nothing(index_elements=["user_id", "recorded_on"])
    )
    db.execute(statement)


def generate_usage_history(
    db: Session, user_id: int, days: int = HISTORY_DAYS, today: date | None = None
) -> None:
    """Create `days` simulated daily readings ending today (no commit)."""
    today = today or utc_today()
    _insert_usage(db, user_id, (today - timedelta(days=offset) for offset in range(days - 1, -1, -1)))


def top_up_usage(db: Session, user_id: int, today: date | None = None) -> None:
    """Fill simulated readings from the last recorded day up to today, then commit."""
    today = today or utc_today()
    window_start = today - timedelta(days=HISTORY_DAYS - 1)
    last = db.scalar(
        select(EnergyUsage.recorded_on)
        .where(EnergyUsage.user_id == user_id)
        .order_by(EnergyUsage.recorded_on.desc())
        .limit(1)
    )
    start = window_start if last is None else max(last + timedelta(days=1), window_start)
    if start <= today:
        _insert_usage(db, user_id, (start + timedelta(days=i) for i in range((today - start).days + 1)))
    db.commit()


# ---------------------------------------------------------- calculations
def days_in_month(day: date) -> int:
    return calendar.monthrange(day.year, day.month)[1]


def estimate_monthly_kwh(recent_kwh: Sequence[float], today: date) -> float:
    """Average daily kWh over the given (last 30 days of) readings x days in the current month."""
    if not recent_kwh:
        return 0.0
    average = sum(recent_kwh) / len(recent_kwh)
    return round(average * days_in_month(today), 2)


def estimate_cost(estimated_kwh: float, price_per_kwh: Decimal, monthly_fee: Decimal) -> Decimal:
    """monthly_fee + estimated kWh x price per kWh, as exact money."""
    return to_money(monthly_fee + Decimal(str(estimated_kwh)) * price_per_kwh)


def daily_energy_cost(kwh: float, price_per_kwh: Decimal) -> Decimal:
    return to_money(Decimal(str(kwh)) * price_per_kwh)


def classify_status(estimated_kwh: float, max_kwh: int) -> EnergyStatus:
    """NORMAL below 80% of the plan limit, HIGH from 80% up to 100%, OVER_LIMIT above 100%."""
    estimated = Decimal(str(estimated_kwh))
    limit = Decimal(max_kwh)
    if estimated < limit * Decimal("0.8"):
        return EnergyStatus.NORMAL
    if estimated <= limit:
        return EnergyStatus.HIGH
    return EnergyStatus.OVER_LIMIT


# --------------------------------------------------------------- queries
def _usage_rows(db: Session, user_id: int, start: date, end: date) -> list[EnergyUsage]:
    stmt = (
        select(EnergyUsage)
        .where(
            EnergyUsage.user_id == user_id,
            EnergyUsage.recorded_on >= start,
            EnergyUsage.recorded_on <= end,
        )
        .order_by(EnergyUsage.recorded_on)
    )
    return list(db.scalars(stmt))


def get_usage(db: Session, user: User, days: int, today: date | None = None) -> EnergyUsageResponse:
    if days not in ALLOWED_RANGES:
        raise BadRequestError("days must be 7, 30 or 90")
    today = today or utc_today()
    plan = resolve_plan(db, user)
    top_up_usage(db, user.id, today)

    window = max(days, 30)  # the monthly estimate always uses the last 30 days
    rows = _usage_rows(db, user.id, today - timedelta(days=window - 1), today)
    history_rows = [r for r in rows if r.recorded_on >= today - timedelta(days=days - 1)]
    recent_kwh = [r.kwh_used for r in rows if r.recorded_on >= today - timedelta(days=29)]

    estimated_kwh = estimate_monthly_kwh(recent_kwh, today)
    return EnergyUsageResponse(
        days=days,
        current_kwh=rows[-1].kwh_used if rows else 0.0,
        estimated_monthly_kwh=estimated_kwh,
        estimated_cost=estimate_cost(estimated_kwh, plan.price_per_kwh, plan.monthly_fee),
        status=classify_status(estimated_kwh, plan.max_kwh),
        plan=_plan_to_out(plan),
        history=[
            UsagePoint(
                date=r.recorded_on,
                kwh=r.kwh_used,
                estimated_cost=daily_energy_cost(r.kwh_used, plan.price_per_kwh),
                is_simulated=r.is_simulated,
            )
            for r in history_rows
        ],
        is_simulated=True,
        disclaimer=SIMULATION_NOTICE,
    )


def get_plans(db: Session, user: User) -> EnergyPlansResponse:
    ensure_default_plans(db)
    plans = db.scalars(
        select(EnergyPlan).where(EnergyPlan.is_active.is_(True)).order_by(EnergyPlan.id)
    ).all()
    db.commit()
    return EnergyPlansResponse(
        current_plan_id=user.energy_plan_id,
        plans=[_plan_to_out(p) for p in plans],
        is_simulated=True,
        disclaimer=SIMULATION_NOTICE,
    )


def get_reports(db: Session, user: User, today: date | None = None) -> EnergyReportsResponse:
    today = today or utc_today()
    plan = resolve_plan(db, user)
    top_up_usage(db, user.id, today)
    rows = _usage_rows(db, user.id, today - timedelta(days=HISTORY_DAYS - 1), today)

    buckets: dict[str, list[float]] = defaultdict(list)
    for row in rows:
        buckets[row.recorded_on.strftime("%Y-%m")].append(row.kwh_used)

    months = []
    for month in sorted(buckets):
        values = buckets[month]
        total = round(sum(values), 2)
        months.append(
            MonthlyReport(
                month=month,
                total_kwh=total,
                average_daily_kwh=round(total / len(values), 2),
                days_recorded=len(values),
                estimated_cost=estimate_cost(total, plan.price_per_kwh, plan.monthly_fee),
            )
        )
    return EnergyReportsResponse(months=months, is_simulated=True, disclaimer=SIMULATION_NOTICE)